name: dynamic_fa_icons
description: Original package to insert FontAwesome icons dynamically in a Flutter app when the icons are not known at compile time.
version: 1.1.0+2
homepage: https://github.com/EdoardoVignati/flutter-dynamic-fa-icons
documentation: https://github.com/EdoardoVignati/flutter-dynamic-fa-icons

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter